language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
script:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker build ./base -t feedthebeast/ftbbase
  - python build.py -m ftbrevelation
services:
  - docker
os: linux
dist: trusty
